//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.Entity.Core.EntityClient;
using System.Data.Entity.Core.Objects;
using System.Data.Entity.Core.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("SISECOOBModel", "Fk_Municipios_Localidades", "Municipios", System.Data.Entity.Core.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SISECOOB.Models.Municipios), "Localidades", System.Data.Entity.Core.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SISECOOB.Models.Localidades), true)]
[assembly: EdmRelationshipAttribute("SISECOOBModel", "FK_Menu_Usuarios_Menu", "Menu", System.Data.Entity.Core.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SISECOOB.Models.Menu), "Menu_Usuarios", System.Data.Entity.Core.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SISECOOB.Models.Menu_Usuarios), true)]

#endregion

namespace SISECOOB.Models
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class SISECOOBEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto SISECOOBEntities usando la cadena de conexión encontrada en la sección 'SISECOOBEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public SISECOOBEntities() : base("name=SISECOOBEntities", "SISECOOBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto SISECOOBEntities.
        /// </summary>
        public SISECOOBEntities(string connectionString) : base(connectionString, "SISECOOBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto SISECOOBEntities.
        /// </summary>
        public SISECOOBEntities(EntityConnection connection) : base(connection, "SISECOOBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Localidades> Localidades
        {
            get
            {
                if ((_Localidades == null))
                {
                    _Localidades = base.CreateObjectSet<Localidades>("Localidades");
                }
                return _Localidades;
            }
        }
        private ObjectSet<Localidades> _Localidades;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Municipios> Municipios
        {
            get
            {
                if ((_Municipios == null))
                {
                    _Municipios = base.CreateObjectSet<Municipios>("Municipios");
                }
                return _Municipios;
            }
        }
        private ObjectSet<Municipios> _Municipios;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<NivelesEducativos> NivelesEducativos
        {
            get
            {
                if ((_NivelesEducativos == null))
                {
                    _NivelesEducativos = base.CreateObjectSet<NivelesEducativos>("NivelesEducativos");
                }
                return _NivelesEducativos;
            }
        }
        private ObjectSet<NivelesEducativos> _NivelesEducativos;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<TipoOficios> TipoOficios
        {
            get
            {
                if ((_TipoOficios == null))
                {
                    _TipoOficios = base.CreateObjectSet<TipoOficios>("TipoOficios");
                }
                return _TipoOficios;
            }
        }
        private ObjectSet<TipoOficios> _TipoOficios;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Zonas> Zonas
        {
            get
            {
                if ((_Zonas == null))
                {
                    _Zonas = base.CreateObjectSet<Zonas>("Zonas");
                }
                return _Zonas;
            }
        }
        private ObjectSet<Zonas> _Zonas;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Conceptos> Conceptos
        {
            get
            {
                if ((_Conceptos == null))
                {
                    _Conceptos = base.CreateObjectSet<Conceptos>("Conceptos");
                }
                return _Conceptos;
            }
        }
        private ObjectSet<Conceptos> _Conceptos;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Menu> Menu
        {
            get
            {
                if ((_Menu == null))
                {
                    _Menu = base.CreateObjectSet<Menu>("Menu");
                }
                return _Menu;
            }
        }
        private ObjectSet<Menu> _Menu;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Menu_Usuarios> Menu_Usuarios
        {
            get
            {
                if ((_Menu_Usuarios == null))
                {
                    _Menu_Usuarios = base.CreateObjectSet<Menu_Usuarios>("Menu_Usuarios");
                }
                return _Menu_Usuarios;
            }
        }
        private ObjectSet<Menu_Usuarios> _Menu_Usuarios;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Localidades. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToLocalidades(Localidades localidades)
        {
            base.AddObject("Localidades", localidades);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Municipios. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToMunicipios(Municipios municipios)
        {
            base.AddObject("Municipios", municipios);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet NivelesEducativos. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToNivelesEducativos(NivelesEducativos nivelesEducativos)
        {
            base.AddObject("NivelesEducativos", nivelesEducativos);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet TipoOficios. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToTipoOficios(TipoOficios tipoOficios)
        {
            base.AddObject("TipoOficios", tipoOficios);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Zonas. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToZonas(Zonas zonas)
        {
            base.AddObject("Zonas", zonas);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Conceptos. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToConceptos(Conceptos conceptos)
        {
            base.AddObject("Conceptos", conceptos);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Menu. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToMenu(Menu menu)
        {
            base.AddObject("Menu", menu);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Menu_Usuarios. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToMenu_Usuarios(Menu_Usuarios menu_Usuarios)
        {
            base.AddObject("Menu_Usuarios", menu_Usuarios);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SISECOOBModel", Name="Conceptos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Conceptos : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Conceptos.
        /// </summary>
        /// <param name="conceptoId">Valor inicial de la propiedad ConceptoId.</param>
        public static Conceptos CreateConceptos(global::System.Int32 conceptoId)
        {
            Conceptos conceptos = new Conceptos();
            conceptos.ConceptoId = conceptoId;
            return conceptos;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ConceptoId
        {
            get
            {
                return _ConceptoId;
            }
            set
            {
                if (_ConceptoId != value)
                {
                    OnConceptoIdChanging(value);
                    ReportPropertyChanging("ConceptoId");
                    _ConceptoId = StructuralObject.SetValidValue(value, "ConceptoId");
                    ReportPropertyChanged("ConceptoId");
                    OnConceptoIdChanged();
                }
            }
        }
        private global::System.Int32 _ConceptoId;
        partial void OnConceptoIdChanging(global::System.Int32 value);
        partial void OnConceptoIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Clave
        {
            get
            {
                return _Clave;
            }
            set
            {
                OnClaveChanging(value);
                ReportPropertyChanging("Clave");
                _Clave = StructuralObject.SetValidValue(value, true, "Clave");
                ReportPropertyChanged("Clave");
                OnClaveChanged();
            }
        }
        private global::System.String _Clave;
        partial void OnClaveChanging(global::System.String value);
        partial void OnClaveChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Concepto
        {
            get
            {
                return _Concepto;
            }
            set
            {
                OnConceptoChanging(value);
                ReportPropertyChanging("Concepto");
                _Concepto = StructuralObject.SetValidValue(value, true, "Concepto");
                ReportPropertyChanged("Concepto");
                OnConceptoChanged();
            }
        }
        private global::System.String _Concepto;
        partial void OnConceptoChanging(global::System.String value);
        partial void OnConceptoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, true, "Descripcion");
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Unidad
        {
            get
            {
                return _Unidad;
            }
            set
            {
                OnUnidadChanging(value);
                ReportPropertyChanging("Unidad");
                _Unidad = StructuralObject.SetValidValue(value, true, "Unidad");
                ReportPropertyChanged("Unidad");
                OnUnidadChanged();
            }
        }
        private global::System.String _Unidad;
        partial void OnUnidadChanging(global::System.String value);
        partial void OnUnidadChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Precio
        {
            get
            {
                return _Precio;
            }
            set
            {
                OnPrecioChanging(value);
                ReportPropertyChanging("Precio");
                _Precio = StructuralObject.SetValidValue(value, "Precio");
                ReportPropertyChanged("Precio");
                OnPrecioChanged();
            }
        }
        private Nullable<global::System.Double> _Precio;
        partial void OnPrecioChanging(Nullable<global::System.Double> value);
        partial void OnPrecioChanged();

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SISECOOBModel", Name="Localidades")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Localidades : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Localidades.
        /// </summary>
        /// <param name="localidadId">Valor inicial de la propiedad LocalidadId.</param>
        public static Localidades CreateLocalidades(global::System.Int32 localidadId)
        {
            Localidades localidades = new Localidades();
            localidades.LocalidadId = localidadId;
            return localidades;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LocalidadId
        {
            get
            {
                return _LocalidadId;
            }
            set
            {
                if (_LocalidadId != value)
                {
                    OnLocalidadIdChanging(value);
                    ReportPropertyChanging("LocalidadId");
                    _LocalidadId = StructuralObject.SetValidValue(value, "LocalidadId");
                    ReportPropertyChanged("LocalidadId");
                    OnLocalidadIdChanged();
                }
            }
        }
        private global::System.Int32 _LocalidadId;
        partial void OnLocalidadIdChanging(global::System.Int32 value);
        partial void OnLocalidadIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MunicipioId_FK
        {
            get
            {
                return _MunicipioId_FK;
            }
            set
            {
                OnMunicipioId_FKChanging(value);
                ReportPropertyChanging("MunicipioId_FK");
                _MunicipioId_FK = StructuralObject.SetValidValue(value, "MunicipioId_FK");
                ReportPropertyChanged("MunicipioId_FK");
                OnMunicipioId_FKChanged();
            }
        }
        private Nullable<global::System.Int32> _MunicipioId_FK;
        partial void OnMunicipioId_FKChanging(Nullable<global::System.Int32> value);
        partial void OnMunicipioId_FKChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, true, "Nombre");
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();

        #endregion

        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SISECOOBModel", "Fk_Municipios_Localidades", "Municipios")]
        public Municipios Municipios
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Municipios>("SISECOOBModel.Fk_Municipios_Localidades", "Municipios").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Municipios>("SISECOOBModel.Fk_Municipios_Localidades", "Municipios").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Municipios> MunicipiosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Municipios>("SISECOOBModel.Fk_Municipios_Localidades", "Municipios");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Municipios>("SISECOOBModel.Fk_Municipios_Localidades", "Municipios", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SISECOOBModel", Name="Menu")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Menu : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Menu.
        /// </summary>
        /// <param name="menuID">Valor inicial de la propiedad MenuID.</param>
        public static Menu CreateMenu(global::System.Int32 menuID)
        {
            Menu menu = new Menu();
            menu.MenuID = menuID;
            return menu;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MenuID
        {
            get
            {
                return _MenuID;
            }
            set
            {
                if (_MenuID != value)
                {
                    OnMenuIDChanging(value);
                    ReportPropertyChanging("MenuID");
                    _MenuID = StructuralObject.SetValidValue(value, "MenuID");
                    ReportPropertyChanged("MenuID");
                    OnMenuIDChanged();
                }
            }
        }
        private global::System.Int32 _MenuID;
        partial void OnMenuIDChanging(global::System.Int32 value);
        partial void OnMenuIDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, true, "Nombre");
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Direccion
        {
            get
            {
                return _Direccion;
            }
            set
            {
                OnDireccionChanging(value);
                ReportPropertyChanging("Direccion");
                _Direccion = StructuralObject.SetValidValue(value, true, "Direccion");
                ReportPropertyChanged("Direccion");
                OnDireccionChanged();
            }
        }
        private global::System.String _Direccion;
        partial void OnDireccionChanging(global::System.String value);
        partial void OnDireccionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Controlador
        {
            get
            {
                return _Controlador;
            }
            set
            {
                OnControladorChanging(value);
                ReportPropertyChanging("Controlador");
                _Controlador = StructuralObject.SetValidValue(value, true, "Controlador");
                ReportPropertyChanged("Controlador");
                OnControladorChanged();
            }
        }
        private global::System.String _Controlador;
        partial void OnControladorChanging(global::System.String value);
        partial void OnControladorChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Padre
        {
            get
            {
                return _Padre;
            }
            set
            {
                OnPadreChanging(value);
                ReportPropertyChanging("Padre");
                _Padre = StructuralObject.SetValidValue(value, "Padre");
                ReportPropertyChanged("Padre");
                OnPadreChanged();
            }
        }
        private Nullable<global::System.Int32> _Padre;
        partial void OnPadreChanging(Nullable<global::System.Int32> value);
        partial void OnPadreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Nivel
        {
            get
            {
                return _Nivel;
            }
            set
            {
                OnNivelChanging(value);
                ReportPropertyChanging("Nivel");
                _Nivel = StructuralObject.SetValidValue(value, "Nivel");
                ReportPropertyChanged("Nivel");
                OnNivelChanged();
            }
        }
        private Nullable<global::System.Int32> _Nivel;
        partial void OnNivelChanging(Nullable<global::System.Int32> value);
        partial void OnNivelChanged();

        #endregion

        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SISECOOBModel", "FK_Menu_Usuarios_Menu", "Menu_Usuarios")]
        public EntityCollection<Menu_Usuarios> Menu_Usuarios
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Menu_Usuarios>("SISECOOBModel.FK_Menu_Usuarios_Menu", "Menu_Usuarios");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Menu_Usuarios>("SISECOOBModel.FK_Menu_Usuarios_Menu", "Menu_Usuarios", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SISECOOBModel", Name="Menu_Usuarios")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Menu_Usuarios : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Menu_Usuarios.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad ID.</param>
        public static Menu_Usuarios CreateMenu_Usuarios(global::System.Int32 id)
        {
            Menu_Usuarios menu_Usuarios = new Menu_Usuarios();
            menu_Usuarios.ID = id;
            return menu_Usuarios;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MenuID_Fk
        {
            get
            {
                return _MenuID_Fk;
            }
            set
            {
                OnMenuID_FkChanging(value);
                ReportPropertyChanging("MenuID_Fk");
                _MenuID_Fk = StructuralObject.SetValidValue(value, "MenuID_Fk");
                ReportPropertyChanged("MenuID_Fk");
                OnMenuID_FkChanged();
            }
        }
        private Nullable<global::System.Int32> _MenuID_Fk;
        partial void OnMenuID_FkChanging(Nullable<global::System.Int32> value);
        partial void OnMenuID_FkChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Usuario_Id
        {
            get
            {
                return _Usuario_Id;
            }
            set
            {
                OnUsuario_IdChanging(value);
                ReportPropertyChanging("Usuario_Id");
                _Usuario_Id = StructuralObject.SetValidValue(value, true, "Usuario_Id");
                ReportPropertyChanged("Usuario_Id");
                OnUsuario_IdChanged();
            }
        }
        private global::System.String _Usuario_Id;
        partial void OnUsuario_IdChanging(global::System.String value);
        partial void OnUsuario_IdChanged();

        #endregion

        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SISECOOBModel", "FK_Menu_Usuarios_Menu", "Menu")]
        public Menu Menu
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Menu>("SISECOOBModel.FK_Menu_Usuarios_Menu", "Menu").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Menu>("SISECOOBModel.FK_Menu_Usuarios_Menu", "Menu").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Menu> MenuReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Menu>("SISECOOBModel.FK_Menu_Usuarios_Menu", "Menu");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Menu>("SISECOOBModel.FK_Menu_Usuarios_Menu", "Menu", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SISECOOBModel", Name="Municipios")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Municipios : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Municipios.
        /// </summary>
        /// <param name="municipioId">Valor inicial de la propiedad MunicipioId.</param>
        public static Municipios CreateMunicipios(global::System.Int32 municipioId)
        {
            Municipios municipios = new Municipios();
            municipios.MunicipioId = municipioId;
            return municipios;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MunicipioId
        {
            get
            {
                return _MunicipioId;
            }
            set
            {
                if (_MunicipioId != value)
                {
                    OnMunicipioIdChanging(value);
                    ReportPropertyChanging("MunicipioId");
                    _MunicipioId = StructuralObject.SetValidValue(value, "MunicipioId");
                    ReportPropertyChanged("MunicipioId");
                    OnMunicipioIdChanged();
                }
            }
        }
        private global::System.Int32 _MunicipioId;
        partial void OnMunicipioIdChanging(global::System.Int32 value);
        partial void OnMunicipioIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, true, "Nombre");
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();

        #endregion

        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SISECOOBModel", "Fk_Municipios_Localidades", "Localidades")]
        public EntityCollection<Localidades> Localidades
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Localidades>("SISECOOBModel.Fk_Municipios_Localidades", "Localidades");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Localidades>("SISECOOBModel.Fk_Municipios_Localidades", "Localidades", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SISECOOBModel", Name="NivelesEducativos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class NivelesEducativos : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto NivelesEducativos.
        /// </summary>
        /// <param name="nivelID">Valor inicial de la propiedad NivelID.</param>
        public static NivelesEducativos CreateNivelesEducativos(global::System.Int32 nivelID)
        {
            NivelesEducativos nivelesEducativos = new NivelesEducativos();
            nivelesEducativos.NivelID = nivelID;
            return nivelesEducativos;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 NivelID
        {
            get
            {
                return _NivelID;
            }
            set
            {
                if (_NivelID != value)
                {
                    OnNivelIDChanging(value);
                    ReportPropertyChanging("NivelID");
                    _NivelID = StructuralObject.SetValidValue(value, "NivelID");
                    ReportPropertyChanged("NivelID");
                    OnNivelIDChanged();
                }
            }
        }
        private global::System.Int32 _NivelID;
        partial void OnNivelIDChanging(global::System.Int32 value);
        partial void OnNivelIDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, true, "Nombre");
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SISECOOBModel", Name="TipoOficios")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TipoOficios : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto TipoOficios.
        /// </summary>
        /// <param name="tipoOficioID">Valor inicial de la propiedad TipoOficioID.</param>
        public static TipoOficios CreateTipoOficios(global::System.Int32 tipoOficioID)
        {
            TipoOficios tipoOficios = new TipoOficios();
            tipoOficios.TipoOficioID = tipoOficioID;
            return tipoOficios;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TipoOficioID
        {
            get
            {
                return _TipoOficioID;
            }
            set
            {
                if (_TipoOficioID != value)
                {
                    OnTipoOficioIDChanging(value);
                    ReportPropertyChanging("TipoOficioID");
                    _TipoOficioID = StructuralObject.SetValidValue(value, "TipoOficioID");
                    ReportPropertyChanged("TipoOficioID");
                    OnTipoOficioIDChanged();
                }
            }
        }
        private global::System.Int32 _TipoOficioID;
        partial void OnTipoOficioIDChanging(global::System.Int32 value);
        partial void OnTipoOficioIDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, true, "Nombre");
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SISECOOBModel", Name="Zonas")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Zonas : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Zonas.
        /// </summary>
        /// <param name="zonaID">Valor inicial de la propiedad ZonaID.</param>
        public static Zonas CreateZonas(global::System.Int32 zonaID)
        {
            Zonas zonas = new Zonas();
            zonas.ZonaID = zonaID;
            return zonas;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ZonaID
        {
            get
            {
                return _ZonaID;
            }
            set
            {
                if (_ZonaID != value)
                {
                    OnZonaIDChanging(value);
                    ReportPropertyChanging("ZonaID");
                    _ZonaID = StructuralObject.SetValidValue(value, "ZonaID");
                    ReportPropertyChanged("ZonaID");
                    OnZonaIDChanged();
                }
            }
        }
        private global::System.Int32 _ZonaID;
        partial void OnZonaIDChanging(global::System.Int32 value);
        partial void OnZonaIDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, true, "Nombre");
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();

        #endregion

    }

    #endregion

}
