//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISECOOB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Text;
    using System.Threading.Tasks;
    using System.Web.Security;

    public partial class Localidades
    {
        public int LocalidadId { get; set; }

        [Display(Name ="Municipio")]
        public Nullable<int> MunicipioId_FK { get; set; }
        public string Nombre { get; set; }
    
        public virtual Municipios Municipios { get; set; }


        public void Crear()
        {
            try
            {

                SISECOOBEntities db = new SISECOOBEntities();
                db.Localidades.Add(this);
                db.SaveChanges();

            }
            catch (Exception e)
            {
                throw e;
            }
        }

        public void Editar()
        {
            try
            {
                SISECOOBEntities db = new SISECOOBEntities();
                Localidades localidad = db.Localidades.FirstOrDefault(u => u.LocalidadId == LocalidadId);
                localidad.Nombre = Nombre;
                localidad.MunicipioId_FK = MunicipioId_FK;
                db.SaveChanges();
            }
            catch (Exception e)
            {
                throw e;
            }
        }

        public void Eliminar(int id)
        {
            try
            {
                SISECOOBEntities db = new SISECOOBEntities();
                var localidades = db.Localidades.FirstOrDefault(i => i.LocalidadId == LocalidadId);
                db.Localidades.Remove(localidades);
                db.SaveChanges();
            }
            catch (Exception e)
            {
                throw e;
            }
        }
    }
}
