//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISECOOB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Localidades
    {
        public int LocalidadId { get; set; }
        public Nullable<int> MunicipioId_FK { get; set; }
        public string Nombre { get; set; }
    
        public virtual Municipios Municipios { get; set; }
    }
}
