//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISECOOB.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    public partial class Municipios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Municipios()
        {
            this.Localidades = new HashSet<Localidades>();
        }
    
        public int MunicipioId { get; set; }
        public string Nombre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Localidades> Localidades { get; set; }

        public void Crear()
        {
            try
            {

                SISECOOBEntities db = new SISECOOBEntities();
                db.Municipios.Add(this);
                db.SaveChanges();
               
            }
            catch (Exception e)
            {
                throw e;
            }
        }

        public void Editar()
        {
            try
            {
                SISECOOBEntities db = new SISECOOBEntities();
                Municipios municipio = db.Municipios.FirstOrDefault(u => u.MunicipioId == MunicipioId);
                municipio.Nombre = Nombre;
                db.SaveChanges();
            }
            catch (Exception e)
            {
                throw e;
            }
        }

        public void Eliminar(int id)
        {
            try
            {
                SISECOOBEntities db = new SISECOOBEntities();
                var municipio = db.Municipios.FirstOrDefault(i => i.MunicipioId == id);
                db.Municipios.Remove(municipio);
                db.SaveChanges();
            }
            catch (Exception e)
            {
                throw e;
            }
        }

    }
}
